Raj Singh Customer Reliability Engineer raj@tailscale.com

diff --git a/clusters/common/apps/default/hello/deployment-curl-hello-world-egress.yaml b/clusters/common/apps/default/hello/deployment-curl-hello-world-egress.yaml
--- a/clusters/common/apps/default/hello/deployment-curl-hello-world-egress.yaml
+++ b/clusters/common/apps/default/hello/deployment-curl-hello-world-egress.yaml
@@ -1,63 +1,63 @@
-# ---
-# apiVersion: v1
-# kind: ConfigMap
-# metadata:
-#   name: curl-hello-world-script-egress
-#   namespace: default
-#   labels:
-#     app: curl-hello-world
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: curl-hello-world-script-egress
+  namespace: default
+  labels:
+    app: curl-hello-world
   
-# data:
-#   curl-loop.sh: |
-#     #!/bin/bash
+data:
+  curl-loop.sh: |
+    #!/bin/bash
 
-#     URL="http://hello-world-egress.default"
-#     INTERVAL=1
-#     echo "Starting infinite curl loop to $URL every $INTERVAL second(s)..."
-#     while true; do
-#         echo -e "\n[$(date)] Sending request to $URL"
-#         curl -s $URL || echo "[$(date)] ❌ Failed to connect"
-#         sleep $INTERVAL
-#     done
-# ---
-# apiVersion: apps/v1
-# kind: Deployment
-# metadata:
-#   name: curl-hello-world-egress
-# spec:
-#   replicas: 1
-#   selector:
-#     matchLabels:
-#       app: curl-hello-world-egress
-#   template:
-#     metadata:
-#       labels:
-#         app: curl-hello-world-egress
-#     spec:
-#       containers:
-#       - name: curl
-#         image: nicolaka/netshoot:latest
-#         command: ["/bin/sh", "/curl-loop.sh"]
-#         volumeMounts:
-#         - name: script
-#           mountPath: /curl-loop.sh
-#           subPath: curl-loop.sh
-#       volumes:
-#       - name: script
-#         configMap:
-#           name: curl-hello-world-script-egress 
-# ---
-# apiVersion: v1
-# kind: Service
-# metadata:
-#   name: hello-world-egress
-#   annotations:
-#     tailscale.com/tailnet-ip: 100.68.181.139
-#     # tailscale.com/proxy-group: common-egress-proxy
-# spec:
-#   externalName: placeholder   # any value - will be overwritten by operator
-#   type: ExternalName 
-#   ports:
-#   - name: http # any value
-#     port: 80
-#     protocol: TCP
+    URL="http://hello-world-egress.default"
+    INTERVAL=1
+    echo "Starting infinite curl loop to $URL every $INTERVAL second(s)..."
+    while true; do
+        echo -e "\n[$(date)] Sending request to $URL"
+        curl -s $URL || echo "[$(date)] ❌ Failed to connect"
+        sleep $INTERVAL
+    done
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: curl-hello-world-egress
+spec:
+  replicas: 1
+  selector:
+    matchLabels:
+      app: curl-hello-world-egress
+  template:
+    metadata:
+      labels:
+        app: curl-hello-world-egress
+    spec:
+      containers:
+      - name: curl
+        image: nicolaka/netshoot:latest
+        command: ["/bin/sh", "/curl-loop.sh"]
+        volumeMounts:
+        - name: script
+          mountPath: /curl-loop.sh
+          subPath: curl-loop.sh
+      volumes:
+      - name: script
+        configMap:
+          name: curl-hello-world-script-egress 
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: hello-world-egress
+  annotations:
+    tailscale.com/tailnet-ip: 100.68.181.139
+    # tailscale.com/proxy-group: common-egress-proxy
+spec:
+  externalName: placeholder   # any value - will be overwritten by operator
+  type: ExternalName 
+  ports:
+  - name: http # any value
+    port: 80
+    protocol: TCP
