fix kustomize check

diff --git a/.github/workflows/kustomize-check.yaml b/.github/workflows/kustomize-check.yaml
--- a/.github/workflows/kustomize-check.yaml
+++ b/.github/workflows/kustomize-check.yaml
@@ -31,8 +31,13 @@ jobs:
       - name: Validate Kustomize builds
         run: |
           find clusters/talos-robbinsdale/apps/* -type d -maxdepth 0 | while read dir; do
-            echo "Validating $dir..."
+            echo "🔍 Validating $dir..."
             if [ -f "$dir/kustomization.yaml" ]; then
-              KUBERNETES_VERSION=1.30.0 kustomize build --enable-helm "$dir" || exit 1
+              if ! KUBERNETES_VERSION=1.29.0 kustomize build --enable-helm "$dir" > /dev/null; then
+                echo "❌ Failed to validate $dir"
+                exit 1
+              else 
+                echo "✅ Successfully validated $dir"
+              fi
             fi
-          done 
+          done
